const pad = (n: number) => String(n).padStart(2, '0')

export const treeStrings = {
  title: 'Cây gia phả',
  loading: 'Đang tải cây gia phả...',
  loadFailed: 'Không tải được cây gia phả.',
  retry: 'Thử lại',
  emptySlot: 'Ô trống',
  generation: (n: number) => `Đời ${pad(n)}`,
  hiddenChildren: (n: number) => `+${n} con`,
  expandHidden: (n: number) => `Hiện ${n} con đang ẩn`,
  canvasLabel: 'Sơ đồ cây gia phả',
  nodeLabel: (name: string, generation: number) => `${name}, Đời ${pad(generation)}`,
  emptyNodeLabel: (generation: number) => `Ô trống, Đời ${pad(generation)}`,
  isMe: 'Tôi',
  fillSlotHint: 'Chọn người điền vào ô trống',
  moreActions: 'Thao tác với ô trống',

  empty: {
    title: 'Cây chưa được dựng',
    description: 'Admin sẽ đưa từng người vào cây. Khi có người trên cây, sơ đồ các đời sẽ hiện ở đây.',
    adminDescription: 'Bắt đầu bằng việc thêm người gốc, rồi thêm con, vợ/chồng từ các nút "+" trên ô.',
  },

  toolbar: {
    addRoot: 'Thêm người gốc',
    search: 'Tìm trên cây',
    searchPlaceholder: 'Gõ họ tên, không cần dấu',
    searchResults: 'Kết quả tìm trên cây',
    searchNoMatch: 'Không có ai tên này trên cây.',
    myAncestors: 'Xem tổ tiên của tôi',
    print: 'In cây',
    showAll: 'Xem toàn cây',
    moreGenerations: 'Hiện thêm 1 đời',
    dragHint: 'Kéo một ô sang ô khác để chuyển nhánh.',
    viewingFrom: (name: string) => `Đang xem cây từ ${name}`,
    viewingAncestors: 'Đang xem tổ tiên của bạn',
    viewingDepth: (n: number) => `Đang hiện ${n} đời quanh người được chọn`,
    notLinked: 'Bạn chưa liên kết tài khoản với thành viên nào nên chưa biết tổ tiên của bạn là ai.',
    notLinkedAction: 'Liên kết "Tôi là ai"',
    notOnTree: 'Bạn chưa có trên cây nên chưa xem được tổ tiên. Nhờ Admin thêm bạn vào cây.',
    searchNotFound: 'Người này không còn trên cây.',
    dismiss: 'Đóng thông báo',
  },

  menu: {
    viewProfile: 'Xem hồ sơ',
    viewFrom: 'Xem cây từ người này',
    viewFromSlot: 'Xem cây từ ô này',
    collapse: 'Thu gọn nhánh',
    expand: 'Mở rộng nhánh',
    adminGroup: 'Chỉnh sửa cây',
    fillSlot: 'Chọn người điền vào ô',
    addChild: 'Thêm con',
    addSpouse: 'Thêm vợ/chồng',
    addParent: 'Thêm cha/mẹ',
    move: 'Di chuyển nhánh',
    reorder: 'Đổi thứ tự',
    setPair: 'Đổi cặp cha–mẹ',
    removeMember: 'Gỡ khỏi cây',
    deleteSlot: 'Xóa ô',
  },

  add: {
    rootTitle: 'Thêm người gốc',
    childTitle: (name: string) => `Thêm con của ${name}`,
    spouseTitle: (name: string) => `Thêm vợ/chồng cho ${name}`,
    parentTitle: (name: string) => `Thêm cha/mẹ của ${name}`,
    fillTitle: 'Điền người vào ô trống',
    rootDescription: 'Chọn một thành viên chưa có trên cây. Người này sẽ đứng ở Đời 01, có thể có nhiều người gốc.',
    childDescription: 'Chọn một thành viên chưa có trên cây làm con.',
    spouseDescription: 'Chọn một thành viên chưa có trên cây làm vợ/chồng, đứng cùng hàng.',
    parentDescription:
      'Người mới sẽ thành gốc ở Đời 01, cả cây dịch xuống một đời. Hệ thống không tự đặt giới tính cho người này.',
    fillDescription: 'Chọn một thành viên chưa có trên cây để điền vào ô này. Vị trí của ô và con cháu giữ nguyên.',
    confirm: 'Thêm vào cây',
    fillConfirm: 'Điền vào ô',
    coParentLabel: 'Con với ai?',
    coParentHint: 'Người này có từ 2 vợ/chồng nên cần chọn mẹ hoặc cha còn lại của con.',
    coParentRequired: 'Vui lòng chọn con này là con với ai.',
    coParentOption: (order: number, name: string) => `Vợ/chồng thứ ${order}: ${name}`,
    picker: {
      search: 'Tìm thành viên',
      searchPlaceholder: 'Gõ họ tên, không cần dấu',
      results: 'Thành viên chưa có trên cây',
      loading: 'Đang tìm thành viên...',
      loadFailed: 'Không tìm được thành viên.',
      retry: 'Thử lại',
      empty: 'Mọi thành viên đều đã có trên cây.',
      noMatch: 'Không có thành viên chưa lên cây nào phù hợp. Thử gõ ngắn hơn.',
      truncated: (shown: number, total: number) => `Đang hiện ${shown}/${total} người. Gõ thêm để thu hẹp.`,
      selected: (name: string) => `Đã chọn: ${name}`,
      clearSelection: 'Bỏ chọn',
      cancel: 'Hủy',
    },
    quickChild: 'Thêm con',
    quickSpouse: 'Thêm vợ/chồng',
    quickParent: 'Thêm cha/mẹ',
    failed: 'Không thêm được vào cây, vui lòng thử lại.',
  },

  remove: {
    title: 'Gỡ khỏi cây?',
    description: (name: string) =>
      `${name} sẽ được gỡ khỏi cây, ô này thành ô trống đúng chỗ cũ. Con cháu và vợ/chồng vẫn giữ nguyên, người này vẫn còn trong danh sách thành viên.`,
    confirm: 'Gỡ khỏi cây',
    cancel: 'Giữ lại',
    failed: 'Không gỡ được khỏi cây, vui lòng thử lại.',
  },

  deleteSlot: {
    title: 'Xóa ô trống?',
    description: 'Ô trống này sẽ bị xóa khỏi cây. Chỉ xóa được khi ô không còn con và không còn vợ/chồng.',
    confirm: 'Xóa ô',
    cancel: 'Giữ lại',
    failed: 'Không xóa được ô, vui lòng thử lại.',
  },

  move: {
    title: (name: string) => `Di chuyển nhánh của ${name}`,
    description:
      'Chọn nơi đến: làm con của một ô khác, hoặc thành gốc mới. Cả nhánh (vợ/chồng và con cháu) đi theo.',
    search: 'Tìm nơi đến',
    searchPlaceholder: 'Gõ họ tên, không cần dấu',
    results: 'Nơi đến',
    asRoot: 'Thành gốc mới (Đời 01)',
    asRootHint: 'Nhánh này đứng riêng như một cây mới.',
    noMatch: 'Không có ô nào phù hợp.',
    noTargets: 'Không còn ô nào khác để chuyển tới.',
    childOf: (name: string) => `Làm con của ${name}`,
    next: 'Tiếp tục',
    coParentLabel: 'Con với ai?',
    coParentHint: 'Ô này có từ 2 vợ/chồng nên cần chọn mẹ hoặc cha còn lại của nhánh.',
    coParentRequired: 'Vui lòng chọn cặp cha–mẹ.',
    confirmTitle: 'Chuyển nhánh này?',
    confirmDescription: (name: string, people: number, empty: number, target: string) =>
      `Nhánh của ${name} gồm ${people} người${empty > 0 ? ` và ${empty} ô trống` : ''} sẽ ${target}. Cả nhánh đi theo, các Đời bên dưới tự dịch theo.`,
    targetRoot: 'thành một cây riêng ở Đời 01',
    targetChildOf: (name: string) => `chuyển sang làm con của ${name}`,
    confirm: 'Chuyển nhánh',
    cancel: 'Hủy',
    back: 'Chọn lại',
    failed: 'Không chuyển được nhánh, vui lòng thử lại.',
    dropCoParentTitle: 'Chọn cặp cha–mẹ',
    dropInvalid: 'Không thả vào đây được',
    dropOnSelf: 'Không thể thả nhánh vào chính nó.',
    dropSpouseHint: 'Người vợ/chồng đi theo người trong dòng, hãy kéo ô của người trong dòng.',
  },

  order: {
    title: (name: string) => `Đổi thứ tự của ${name}`,
    description: 'Đổi chỗ với người anh em kề bên. Anh em xếp từ trái sang phải.',
    left: 'Sang trái',
    right: 'Sang phải',
    close: 'Xong',
    failed: 'Không đổi được thứ tự, vui lòng thử lại.',
    position: (index: number, total: number) => `Đang ở vị trí ${index}/${total}`,
  },

  pair: {
    title: (name: string) => `Đổi cặp cha–mẹ của ${name}`,
    description: 'Chọn người con này là con của cha/mẹ nào trong các cặp bên dưới.',
    option: (order: number, name: string) => `Vợ/chồng thứ ${order}: ${name}`,
    current: 'Đang chọn',
    confirm: 'Lưu',
    cancel: 'Hủy',
    failed: 'Không đổi được cặp cha–mẹ, vui lòng thử lại.',
  },

  errors: {
    generic: 'Có lỗi xảy ra, vui lòng thử lại.',
  },

  print: {
    title: 'In cây khổ lớn',
    root: 'Người gốc',
    rootAll: 'Toàn bộ cây (mọi gốc)',
    rootOption: (generation: number, name: string) => `Đời ${pad(generation)} · ${name}`,
    rootHint: 'Chọn một người để chỉ in nhánh của người đó (cùng vợ/chồng và con cháu).',
    paper: 'Khổ giấy',
    orientation: 'Hướng giấy',
    portrait: 'Dọc',
    landscape: 'Ngang',
    format: 'Định dạng',
    withPhotos: 'In kèm ảnh đại diện',
    photosHint: 'Bỏ chọn nếu muốn file nhẹ hơn.',
    summary: (people: number, generations: number) => `Cây có ${people} người, ${generations} đời.`,
    pdfPlan: (pages: number, paper: string, orientation: string) =>
      pages === 1
        ? `PDF: 1 trang ${paper} ${orientation}, chữ vector, phóng to không vỡ.`
        : `PDF: ${pages} trang ${paper} ${orientation}. In ra rồi ghép theo dấu cắt ở bốn góc.`,
    pngPlan: (width: number, height: number, dpi: number) => `PNG: ${width}×${height} điểm ảnh, khoảng ${dpi} dpi.`,
    pngLowDpi: 'Cây quá lớn nên ảnh PNG sẽ không nét khi in. Hãy chọn PDF hoặc chọn một nhánh nhỏ hơn.',
    cancel: 'Đóng',
    stop: 'Dừng',
    create: 'Tạo file',
    stages: {
      fonts: 'Đang tải font...',
      photos: (done: number, total: number) => `Đang tải ảnh đại diện (${done}/${total})...`,
      layout: (percent: number) => `Đang dựng sơ đồ (${percent}%)...`,
      pages: (done: number, total: number) => `Đang tạo trang PDF (${done}/${total})...`,
      image: 'Đang tạo ảnh PNG...',
    },
    done: 'Đã tạo xong, file đang được tải về.',
    aborted: 'Đã dừng.',
    failed: 'Không tạo được file. Cây có thể quá lớn cho máy này, hãy thử chọn nhánh nhỏ hơn hoặc bỏ ảnh đại diện.',
    // In trên giấy
    docTitle: 'Cây gia phả',
    docTitleBranch: (name: string) => `Cây gia phả · nhánh ${name}`,
    docSubtitle: (people: number, date: string) => `${people} người · in ngày ${date}`,
    generationLabel: (n: number) => `Đời ${pad(n)}`,
    pageLabel: (page: number, total: number, row: number, col: number) =>
      `Trang ${page}/${total} · hàng ${row}, cột ${col}`,
    fileName: (paper: string, orientation: string, ext: string) => `cay-gia-pha-${paper}-${orientation}.${ext}`,
    orientationSlug: { portrait: 'doc', landscape: 'ngang' },
  },

  dev: {
    title: 'Kiểm tra layout cây',
    intro: 'Trang chỉ có ở chế độ dev, vẽ thô kết quả của layoutTree từ các đồ thị mẫu viết sẵn.',
    samples: 'Ca mẫu',
    maxDepth: 'Số đời hiện',
    allDepth: 'Tất cả',
    depthOption: (n: number) => `${n} đời`,
    hint: 'Bấm vào một ô để chọn, rồi thu gọn nhánh hoặc xem cây từ ô đó.',
    selected: (id: number) => `Đang chọn ô ${id}`,
    collapse: 'Thu gọn nhánh',
    expand: 'Mở nhánh',
    viewFrom: 'Xem từ ô này',
    viewAll: 'Về toàn cây',
    generation: (n: number) => `Đời ${String(n).padStart(2, '0')}`,
    hidden: (n: number) => `+${n} con`,
    diagramLabel: 'Sơ đồ cây mẫu',
  },
}
