// Chuỗi UI của module calendar (không dùng i18n, chỉ tiếng Việt)
import { MAX_YEAR, MIN_YEAR } from '@/utils/lunar'

export const calendarStrings = {
  converter: {
    title: 'Đổi lịch âm – dương',
    description:
      'Chọn nhập theo dương lịch hoặc âm lịch, ngày ở lịch còn lại hiện ngay bên dưới. Tính theo giờ Việt Nam (UTC+7).',
    field: 'Ngày cần đổi',
    today: 'Hôm nay',
    range: `Hỗ trợ năm dương ${MIN_YEAR}–${MAX_YEAR}. Với âm lịch, nhớ tick “Tháng nhuận” nếu là tháng nhuận.`,
  },
  page: {
    title: 'Sự kiện',
    tabsLabel: 'Chế độ xem sự kiện',
    upcoming: 'Sắp tới',
    month: 'Lịch tháng',
    addEvent: 'Thêm sự kiện',
    proposeEvent: 'Đề xuất sự kiện',
  },
  types: {
    MEMORIAL: 'Giỗ',
    BIRTHDAY: 'Sinh nhật',
    CUSTOM: 'Sự kiện chung',
  },
  legend: {
    title: 'Chú giải',
  },
  upcoming: {
    range: 'Khoảng thời gian',
    type: 'Loại',
    sort: 'Sắp xếp',
    allTypes: 'Tất cả',
    days: { 7: '7 ngày tới', 15: '15 ngày tới', 30: '30 ngày tới', 90: '90 ngày tới', 365: 'Cả năm' },
    sortAsc: 'Gần nhất trước',
    sortDesc: 'Xa nhất trước',
    empty: 'Không có sự kiện nào',
    emptyHint: 'Thử chọn khoảng thời gian dài hơn hoặc bỏ lọc loại sự kiện.',
    emptyAdmin: 'Thêm sự kiện chung hoặc nhập ngày mất, ngày sinh vào hồ sơ thành viên để có lịch nhắc.',
    loadFailed: 'Không tải được danh sách sự kiện.',
    retry: 'Thử lại',
  },
  month: {
    lunarToggle: 'Xem theo âm',
    lunarToggleHint: 'Ngày âm hiện lớn, ngày dương hiện nhỏ',
    prev: 'Tháng trước',
    next: 'Tháng sau',
    today: 'Hôm nay',
    weekdays: ['T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'CN'],
    weekdayNames: ['Thứ hai', 'Thứ ba', 'Thứ tư', 'Thứ năm', 'Thứ sáu', 'Thứ bảy', 'Chủ nhật'],
    loadFailed: 'Không tải được lịch tháng này.',
    outOfRange: `Lịch chỉ hỗ trợ từ năm ${MIN_YEAR} đến ${MAX_YEAR}.`,
    noEvents: 'Không có sự kiện',
    weekOf: (from: string, to: string) => `Tuần ${from} – ${to}`,
  },
  day: {
    empty: 'Ngày này chưa có sự kiện nào.',
    addHere: 'Thêm sự kiện vào ngày này',
  },
  occurrence: {
    today: 'Hôm nay',
    tomorrow: 'Ngày mai',
    inDays: (n: number) => `còn ${n} ngày`,
    agoDays: (n: number) => `${n} ngày trước`,
    memorialNth: (n: number) => `giỗ lần thứ ${n}`,
    birthdayAge: (n: number) => `tròn ${n} tuổi`,
    edit: 'Sửa sự kiện',
    viewMember: 'Xem hồ sơ',
  },
  form: {
    createTitle: 'Thêm sự kiện chung',
    editTitle: 'Sửa sự kiện chung',
    proposeCreateTitle: 'Đề xuất sự kiện',
    proposeEditTitle: 'Đề xuất sửa sự kiện',
    title: 'Tên sự kiện',
    description: 'Ghi chú',
    descriptionHint: 'Không bắt buộc. Địa điểm, giờ, người phụ trách...',
    repeat: 'Kiểu lặp',
    repeatYearly: 'Lặp hằng năm',
    repeatOnce: 'Chỉ một lần',
    date: 'Ngày diễn ra',
    dateYearlyHint: 'Nhập ngày và tháng, để trống năm. Sự kiện âm lịch theo quy tắc ngày cúng: tháng nhuận tính vào tháng thường, ngày 30 của tháng thiếu tính ngày 29.',
    dateOnceHint: 'Nhập đủ ngày, tháng và năm.',
    save: 'Lưu',
    cancel: 'Hủy',
    delete: 'Xóa sự kiện',
    proposeDelete: 'Đề xuất xóa',
    saveFailed: 'Không lưu được sự kiện, vui lòng thử lại.',
    sendProposal: 'Gửi đề xuất',
    titleRequired: 'Vui lòng nhập tên sự kiện.',
    titleTooLong: 'Tên sự kiện tối đa 200 ký tự.',
    descriptionTooLong: 'Ghi chú tối đa 2000 ký tự.',
    loadFailed: 'Không tải được sự kiện này.',
    deleteConfirmTitle: 'Xóa sự kiện này?',
    deleteConfirmBody: (title: string) =>
      `Sự kiện “${title}” sẽ bị xóa khỏi lịch. Thao tác này không hoàn tác được.`,
    deleteConfirm: 'Xóa',
    deleteFailed: 'Không xóa được sự kiện, vui lòng thử lại.',
  },
} as const
