export const memberStrings = {
  list: {
    title: 'Thành viên',
    searchPlaceholder: 'Tìm họ tên...',
    emptyState: {
      noDataTitle: 'Chưa có thành viên nào',
      noDataDesc: 'Gia phả hiện chưa có thông tin thành viên.',
      noMatchTitle: 'Không tìm thấy kết quả',
      noMatchDesc: 'Vui lòng thử lại với từ khóa hoặc bộ lọc khác.',
    },
    filters: {
      sort: 'Sắp xếp',
      sortOptions: {
        name: 'Tên A-Z',
        age: 'Tuổi',
        created: 'Mới thêm',
        generation: 'Đời',
      },
      deceased: {
        label: 'Trạng thái',
        all: 'Trạng thái: Tất cả',
        alive: 'Còn sống',
        dead: 'Đã mất',
      },
      onTree: {
        label: 'Cây gia phả',
        all: 'Cây gia phả: Tất cả',
        yes: 'Đã có',
        no: 'Chưa có',
      },
    },
  },
  detail: {
    title: 'Hồ sơ thành viên',
    born: 'Sinh',
    died: 'Mất',
    generation: 'Đời',
    burialPlace: 'Nơi an táng',
    phone: 'Số điện thoại',
    email: 'Email',
    gender: {
      M: 'Nam',
      F: 'Nữ',
      unknown: 'Trung tính',
    },
    sections: {
      relatives: 'Người thân',
      tree: 'Trên cây',
      attachments: 'Tệp đính kèm',
    },
    tabooName: 'Tên húy',
    biography: 'Tiểu sử',
    calendarSuffix: { lunar: 'âm lịch', solar: 'dương lịch' },
    comingSoon: 'Chức năng sẽ có ở các đợt tiếp theo.',
    you: 'Đây là bạn',
  },
  // Khối "Trên cây" của trang chi tiết (IDEA §6.1)
  onTree: {
    loading: 'Đang tải thông tin trên cây...',
    loadFailed: 'Không tải được thông tin trên cây.',
    notOnTree: 'Người này chưa có trên cây gia phả.',
    notOnTreeAdmin: 'Người này chưa có trên cây gia phả. Admin thêm người này từ trang Cây.',
    generation: 'Đời',
    parents: 'Cha/mẹ',
    spouses: 'Vợ/chồng',
    children: 'Con theo cây',
    none: 'Chưa có',
    emptySlot: 'Ô trống',
    spouseOrder: (order: number) => `thứ ${order}`,
    viewOnTree: 'Xem trên cây',
  },
  actions: {
    add: 'Thêm thành viên',
    edit: 'Sửa hồ sơ',
    editMine: 'Sửa hồ sơ của tôi',
    remove: 'Xóa',
  },
  form: {
    createTitle: 'Thêm thành viên',
    editTitle: 'Sửa hồ sơ',
    createSubmit: 'Thêm thành viên',
    editSubmit: 'Lưu thay đổi',
    cancel: 'Hủy',
    notFound: 'Không tìm thấy thành viên',
    notFoundDesc: 'Người này có thể đã bị xóa hoặc không tồn tại.',
    forbidden: 'Bạn không sửa được hồ sơ này',
    forbiddenDesc: 'Bạn chỉ sửa được hồ sơ của chính mình. Admin sửa được mọi hồ sơ.',
    sections: {
      basic: 'Thông tin cơ bản',
      birth: 'Ngày sinh',
      contact: 'Liên hệ',
      biography: 'Tiểu sử',
      death: 'Đã qua đời',
    },
    fullName: 'Họ tên',
    fullNameHint: 'Ghi nguyên văn, có thể kèm "Cụ", "Ông", "Bà" hoặc "(Tức ...)".',
    tabooName: 'Tên húy',
    gender: 'Giới tính',
    genderOptions: { none: 'Chưa rõ', M: 'Nam', F: 'Nữ' },
    labels: 'Nhãn đặc biệt',
    labelsHint: 'Ví dụ "Liệt sỹ". Ngăn cách nhiều nhãn bằng dấu phẩy.',
    birthDate: 'Ngày sinh',
    birthHint:
      'Có thể chỉ nhập năm. Sinh nhật hằng năm tính theo lịch đang chọn ở trên (Dương hoặc Âm).',
    phone: 'Số điện thoại',
    email: 'Email liên hệ',
    contactHint: 'Chỉ Admin và chính chủ hồ sơ xem được. Tách biệt với email đăng nhập.',
    biography: 'Tiểu sử',
    isDeceased: 'Đã qua đời',
    deathLocked: 'Chỉ Admin sửa được phần này.',
    deathDate: 'Ngày mất',
    deathHint: 'Chỉ biết ngày/tháng âm thì chọn Âm lịch và bỏ trống năm.',
    memorialTitle: 'Ngày giỗ ghi đè (âm lịch)',
    memorialHint: 'Chỉ điền khi gia đình cúng giỗ vào ngày khác ngày mất.',
    memorialDay: 'Ngày',
    memorialMonth: 'Tháng',
    burialPlace: 'Nơi an táng',
    saveFailed: 'Không lưu được hồ sơ.',
    avatarFailed: (reason: string) => `Đã lưu hồ sơ nhưng chưa tải được ảnh đại diện: ${reason}`,
  },
  avatar: {
    label: 'Ảnh đại diện',
    choose: 'Chọn ảnh',
    change: 'Đổi ảnh',
    clear: 'Bỏ ảnh đã chọn',
    hint: 'JPG, PNG hoặc WebP, tối đa 10 MB.',
    mockHint: 'Cần kết nối máy chủ: ở chế độ giả lập chưa tải ảnh lên được.',
    badType: 'Chỉ nhận ảnh JPG, PNG hoặc WebP.',
    tooBig: 'Ảnh quá lớn, tối đa 10 MB. Hãy chọn ảnh nhỏ hơn.',
  },
  remove: {
    title: 'Xóa thành viên này?',
    description: (name: string) =>
      `Hồ sơ "${name}" sẽ bị xóa, kể cả các dòng người thân liên quan. Admin vẫn xem lại được bản sao ở mục "Thành viên đã xóa".`,
    confirm: 'Xóa thành viên',
    cancel: 'Hủy',
    onTree: 'Không xóa được vì người này đang có trên cây. Hãy gỡ người này khỏi cây trước.',
  },
  relatives: {
    title: 'Người thân',
    add: 'Thêm người thân',
    listLabel: 'Danh sách người thân',
    // "Tên — nhãn": nhãn do chủ hồ sơ tự nhập, ví dụ "cha", "vợ", "chú họ"
    separator: '—',
    empty: 'Chưa có người thân nào.',
    emptyEditable: 'Chưa có người thân nào. Bấm "Thêm người thân" để khai báo.',
    loading: 'Đang tải danh sách người thân',
    loadFailed: 'Không tải được danh sách người thân.',
    retry: 'Thử lại',
    edit: (name: string) => `Sửa nhãn của ${name}`,
    remove: (name: string) => `Xóa ${name} khỏi danh sách người thân`,
    oneWayHint: 'Dòng này chỉ nằm trong hồ sơ này, hồ sơ của người thân không tự có dòng ngược lại.',
    picker: {
      title: 'Thêm người thân',
      description: 'Chọn một thành viên đã có, rồi nhập người đó là gì của chủ hồ sơ. Chưa có trong danh sách thì nhờ Admin tạo trước.',
      confirm: 'Thêm người thân',
      search: 'Tìm thành viên',
      searchPlaceholder: 'Gõ họ tên, không cần dấu',
      results: 'Kết quả tìm thành viên',
      loading: 'Đang tìm thành viên...',
      loadFailed: 'Không tìm được thành viên.',
      retry: 'Thử lại',
      empty: 'Chưa có thành viên nào để chọn.',
      noMatch: 'Không tìm thấy thành viên phù hợp. Thử gõ ngắn hơn.',
      truncated: (shown: number, total: number) => `Đang hiện ${shown}/${total} người. Gõ thêm để thu hẹp.`,
      selected: (name: string) => `Đã chọn: ${name}`,
      clearSelection: 'Bỏ chọn',
      cancel: 'Hủy',
      owner: 'Chủ hồ sơ',
      alreadyAdded: 'Đã có trong danh sách',
    },
    label: 'Người này là gì của chủ hồ sơ?',
    labelHint: 'Ví dụ "cha", "vợ", "chú họ". Tối đa 50 ký tự.',
    labelRequired: 'Vui lòng nhập nhãn, ví dụ "cha", "vợ", "chú họ".',
    labelTooLong: 'Nhãn tối đa 50 ký tự.',
    editTitle: 'Sửa nhãn',
    editSubmit: 'Lưu nhãn',
    editCancel: 'Hủy',
    removeTitle: 'Xóa người thân này?',
    removeDescription: (name: string, label: string) =>
      `"${name} — ${label}" sẽ bị xóa khỏi danh sách người thân của hồ sơ này. Hồ sơ của ${name} vẫn giữ nguyên.`,
    removeConfirm: 'Xóa',
    removeCancel: 'Hủy',
    failed: 'Có lỗi xảy ra, vui lòng thử lại.',
  },
}
