/// <reference lib="webworker" />
declare let self: ServiceWorkerGlobalScope

import { clientsClaim } from 'workbox-core'
import { cleanupOutdatedCaches, precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching'
import { registerRoute, NavigationRoute } from 'workbox-routing'
import { NetworkFirst } from 'workbox-strategies'

self.skipWaiting()
clientsClaim()

// Clean old caches
cleanupOutdatedCaches()

// Precache all assets generated by build
precacheAndRoute(self.__WB_MANIFEST)

// Let SPA handle all navigations
try {
  const handler = createHandlerBoundToURL('/index.html')
  const navigationRoute = new NavigationRoute(handler, {
    denylist: [/^\/api\//],
  })
  registerRoute(navigationRoute)
} catch {
  // Catch errors in dev mode
}

// Cache API requests using NetworkFirst, allowing offline read access to cached data.
// We exclude auth-related endpoints (/api/auth/** and /api/me) for security/consistency.
// Only GET requests are cached (mutations should require network).
registerRoute(
  ({ url, request }) => {
    if (request.method !== 'GET') return false
    if (!url.pathname.startsWith('/api/')) return false
    
    // Exclude auth and me
    if (url.pathname.startsWith('/api/auth/')) return false
    if (url.pathname === '/api/me') return false

    return true
  },
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 3,
  })
)

// Thông báo đẩy: phải luôn gọi showNotification (userVisibleOnly), nếu không Chrome hiện "trang đã được cập nhật ở nền" rồi có thể thu hồi quyền
self.addEventListener('push', (event) => {
  let data: { title?: string; body?: string; tag?: string; url?: string | null }
  try {
    data = event.data?.json() ?? {}
  } catch {
    data = { body: event.data?.text() }
  }

  event.waitUntil(
    self.registration.showNotification(data.title || 'Tộc Phả', {
      body: data.body,
      icon: '/pwa-192x192.png',
      badge: '/pwa-192x192.png',
      // Mỗi bản tin một thẻ riêng: dùng chung thẻ "digest" thì bản mới đè bản cũ chưa đọc và không kêu lại
      tag: data.tag ? `${data.tag}-${Date.now()}` : undefined,
      data: { url: data.url || '/' },
    }),
  )
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const url = new URL((event.notification.data as { url?: string } | null)?.url || '/', self.location.origin).href
  event.waitUntil(
    (async () => {
      const windows = await self.clients.matchAll({ type: 'window', includeUncontrolled: true })
      const open = windows.find((w) => 'focus' in w)
      if (open) {
        await open.focus()
        if ('navigate' in open) await open.navigate(url)
      } else {
        await self.clients.openWindow(url)
      }
    })(),
  )
})
