/// <reference lib="webworker" />
declare let self: ServiceWorkerGlobalScope

import { clientsClaim } from 'workbox-core'
import { cleanupOutdatedCaches, precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching'
import { registerRoute, NavigationRoute } from 'workbox-routing'
import { NetworkFirst } from 'workbox-strategies'

self.skipWaiting()
clientsClaim()

// Clean old caches
cleanupOutdatedCaches()

// Precache all assets generated by build
precacheAndRoute(self.__WB_MANIFEST)

// Let SPA handle all navigations
try {
  const handler = createHandlerBoundToURL('/index.html')
  const navigationRoute = new NavigationRoute(handler, {
    denylist: [/^\/api\//],
  })
  registerRoute(navigationRoute)
} catch (e) {
  // Catch errors in dev mode
}

// Cache API requests using NetworkFirst, allowing offline read access to cached data.
// We exclude auth-related endpoints (/api/auth/** and /api/me) for security/consistency.
// Only GET requests are cached (mutations should require network).
registerRoute(
  ({ url, request }) => {
    if (request.method !== 'GET') return false
    if (!url.pathname.startsWith('/api/')) return false
    
    // Exclude auth and me
    if (url.pathname.startsWith('/api/auth/')) return false
    if (url.pathname === '/api/me') return false

    return true
  },
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 3,
  })
)

// Handle push notifications (for Phase 21)
self.addEventListener('push', (event) => {
  const data = event.data?.json() ?? {}
  const title = data.title || 'Tộc Phả'
  
  event.waitUntil(
    self.registration.showNotification(title, {
      body: data.body,
      icon: '/pwa-192x192.png',
      badge: '/pwa-192x192.png',
      tag: data.tag,
      data: data.url
    })
  )
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  if (event.notification.data) {
    event.waitUntil(
      self.clients.openWindow(event.notification.data)
    )
  }
})
